// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: hello_grpc.proto

package hello_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloRPCClient is the client API for HelloRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloRPCClient interface {
	SayHello(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type helloRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloRPCClient(cc grpc.ClientConnInterface) HelloRPCClient {
	return &helloRPCClient{cc}
}

func (c *helloRPCClient) SayHello(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/hello_grpc.HelloRPC/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloRPCServer is the server API for HelloRPC service.
// All implementations must embed UnimplementedHelloRPCServer
// for forward compatibility
type HelloRPCServer interface {
	SayHello(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedHelloRPCServer()
}

// UnimplementedHelloRPCServer must be embedded to have forward compatible implementations.
type UnimplementedHelloRPCServer struct {
}

func (UnimplementedHelloRPCServer) SayHello(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloRPCServer) mustEmbedUnimplementedHelloRPCServer() {}

// UnsafeHelloRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloRPCServer will
// result in compilation errors.
type UnsafeHelloRPCServer interface {
	mustEmbedUnimplementedHelloRPCServer()
}

func RegisterHelloRPCServer(s grpc.ServiceRegistrar, srv HelloRPCServer) {
	s.RegisterService(&HelloRPC_ServiceDesc, srv)
}

func _HelloRPC_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloRPCServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello_grpc.HelloRPC/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloRPCServer).SayHello(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloRPC_ServiceDesc is the grpc.ServiceDesc for HelloRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello_grpc.HelloRPC",
	HandlerType: (*HelloRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloRPC_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello_grpc.proto",
}
